language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  #- pip install . --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse --use-mirrors; fi"
# command to run tests
script:
  - nosetests --with-coverage --cover-package=splitleafs,test_splitleafs
after_success:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install python-coveralls --use-mirrors; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi"
